### ISSUE TITLE
Documents from which vectordb was made

### ISSUE THREAD

**Issue by FaizanFaisal25** [jwoongkim11/QA-RAG#1]
Hello, 

I am reaching out regarding the Data folder which has the FAISS DB. I am interested in gaining access to the source documents that were used in its creation. Let me know if you still have access to those and can share.

Thanks!

**Comment by jwoongkim11** [comment]
Hello,

Thank you for your interest in the Data folder. Regarding the source documents used in its creation, you'll be pleased to know that much of the data is based on publicly available guidelines.

For your convenience, you can access the FDA guidelines at this link: [FDA Guidelines](https://www.fda.gov/drugs/guidance-compliance-regulatory-information/guidances-drugs). Additionally, the ICH guidelines, which have also been instrumental in the creation of the DB, can be found here: [ICH Guidelines](https://www.ich.org/page/quality-guidelines).

Please let me know if you need further assistance or have any other questions.

Thanks!
